.\Release\diagTruth.exe D:\Repo\Segmented\AKa2\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKa3\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKa4\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKs3\ T9 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKs5\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKs6\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKs7\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\AKs8\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\Ble\ T9 S1
.\Release\diagTruth.exe D:\Repo\Segmented\C002\ T6 S1
.\Release\diagTruth.exe D:\Repo\Segmented\case_2\ T9 L5
.\Release\diagTruth.exe D:\Repo\Segmented\case_10\ T10 L5
.\Release\diagTruth.exe D:\Repo\Segmented\DzZ_T1\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\DzZ_T2\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\F02\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\F03\ T12 S1
.\Release\diagTruth.exe D:\Repo\Segmented\F04\ T2 S1
.\Release\diagTruth.exe D:\Repo\Segmented\Geh\ T12 S1
.\Release\diagTruth.exe D:\Repo\Segmented\Hoe\ T11 S1
.\Release\diagTruth.exe D:\Repo\Segmented\Lan\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\LanII\ T10 S1
.\Release\diagTruth.exe D:\Repo\Segmented\lc\ T12 S1
.\Release\diagTruth.exe D:\Repo\Segmented\S01\ T12 S1
.\Release\diagTruth.exe D:\Repo\Segmented\S02\ T11 S1
.\Release\diagTruth.exe D:\Repo\Segmented\Sch\ T11 L5
.\Release\diagTruth.exe D:\Repo\Segmented\St1\ T11 S1