.\Release\gcCompare.exe BB AKa2.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKa2\ T10 S1
.\Release\gcCompare.exe BB AKa3.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKa3\ T10 S1
.\Release\gcCompare.exe BB AKa4.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKa4\ T10 S1
.\Release\gcCompare.exe BB AKs3.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKs3\ T9 S1
.\Release\gcCompare.exe BB AKs5.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKs5\ T10 S1
.\Release\gcCompare.exe BB AKs6.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKs6\ T10 S1
.\Release\gcCompare.exe BB AKs7.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKs7\ T10 S1
.\Release\gcCompare.exe BB AKs8.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\AKs8\ T10 S1
.\Release\gcCompare.exe BB Ble.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\Ble\ T9 S1
.\Release\gcCompare.exe BB C002.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\C002\ T6 S1
.\Release\gcCompare.exe BB case_2.nii Outline D:\Repo\PhDthesis\cr\BB-Optimal\case_2\ T9 L5
.\Release\gcCompare.exe BB case_10.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\case_10\ T10 L5
.\Release\gcCompare.exe BB DzZ_T1.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\DzZ_T1\ T10 S1
.\Release\gcCompare.exe BB DzZ_T2.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\DzZ_T2\ T10 S1
.\Release\gcCompare.exe BB F02.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\F02\ T10 S1
.\Release\gcCompare.exe BB F03.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\F03\ T12 S1
.\Release\gcCompare.exe BB F04.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\F04\ T2 S1
.\Release\gcCompare.exe BB Geh.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\Geh\ T12 S1
.\Release\gcCompare.exe BB Hoe.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\Hoe\ T11 S1
.\Release\gcCompare.exe BB Lan.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\Lan\ T10 S1
.\Release\gcCompare.exe BB LanII.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\LanII\ T10 S1
.\Release\gcCompare.exe BB LC.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\LC\ T12 S1
.\Release\gcCompare.exe BB S01.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\S01\ T12 S1
.\Release\gcCompare.exe BB S02.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\S02\ T11 S1
.\Release\gcCompare.exe BB Sch.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\Sch\ T11 L5
.\Release\gcCompare.exe BB St1.dcm Outline D:\Repo\PhDthesis\cr\BB-Optimal\St1\ T11 S1