.\Release\gcCompare.exe AI AKa2.dcm Centers D:\Repo\PhDthesis\cr\AI\AKa2\ T10 S1
.\Release\gcCompare.exe AI AKa3.dcm Centers D:\Repo\PhDthesis\cr\AI\AKa3\ T10 S1
.\Release\gcCompare.exe AI AKa4.dcm Centers D:\Repo\PhDthesis\cr\AI\AKa4\ T10 S1
.\Release\gcCompare.exe AI AKs3.dcm Centers D:\Repo\PhDthesis\cr\AI\AKs3\ T9 S1
.\Release\gcCompare.exe AI AKs5.dcm Centers D:\Repo\PhDthesis\cr\AI\AKs5\ T10 S1
.\Release\gcCompare.exe AI AKs6.dcm Centers D:\Repo\PhDthesis\cr\AI\AKs6\ T10 S1
.\Release\gcCompare.exe AI AKs7.dcm Centers D:\Repo\PhDthesis\cr\AI\AKs7\ T10 S1
.\Release\gcCompare.exe AI AKs8.dcm Centers D:\Repo\PhDthesis\cr\AI\AKs8\ T10 S1
.\Release\gcCompare.exe AI Ble.dcm Centers D:\Repo\PhDthesis\cr\AI\Ble\ T9 S1
.\Release\gcCompare.exe AI C002.dcm Centers D:\Repo\PhDthesis\cr\AI\C002\ T6 S1
.\Release\gcCompare.exe AI case_2.nii Centers D:\Repo\PhDthesis\cr\AI\case_2\ T9 L5
.\Release\gcCompare.exe AI case_10.dcm Centers D:\Repo\PhDthesis\cr\AI\case_10\ T10 L5
.\Release\gcCompare.exe AI DzZ_T1.dcm Centers D:\Repo\PhDthesis\cr\AI\DzZ_T1\ T10 S1
.\Release\gcCompare.exe AI DzZ_T2.dcm Centers D:\Repo\PhDthesis\cr\AI\DzZ_T2\ T10 S1
.\Release\gcCompare.exe AI F02.dcm Centers D:\Repo\PhDthesis\cr\AI\F02\ T10 S1
.\Release\gcCompare.exe AI F03.dcm Centers D:\Repo\PhDthesis\cr\AI\F03\ T12 S1
.\Release\gcCompare.exe AI F04.dcm Centers D:\Repo\PhDthesis\cr\AI\F04\ T2 S1
.\Release\gcCompare.exe AI Geh.dcm Centers D:\Repo\PhDthesis\cr\AI\Geh\ T12 S1
.\Release\gcCompare.exe AI Hoe.dcm Centers D:\Repo\PhDthesis\cr\AI\Hoe\ T11 S1
.\Release\gcCompare.exe AI Lan.dcm Centers D:\Repo\PhDthesis\cr\AI\Lan\ T10 S1
.\Release\gcCompare.exe AI LanII.dcm Centers D:\Repo\PhDthesis\cr\AI\LanII\ T10 S1
.\Release\gcCompare.exe AI LC.dcm Centers D:\Repo\PhDthesis\cr\AI\LC\ T12 S1
.\Release\gcCompare.exe AI S01.dcm Centers D:\Repo\PhDthesis\cr\AI\S01\ T12 S1
.\Release\gcCompare.exe AI S02.dcm Centers D:\Repo\PhDthesis\cr\AI\S02\ T11 S1
.\Release\gcCompare.exe AI Sch.dcm Centers D:\Repo\PhDthesis\cr\AI\Sch\ T11 L5
.\Release\gcCompare.exe AI St1.dcm Centers D:\Repo\PhDthesis\cr\AI\St1\ T11 S1