.\Release\gcCompare.exe BB AKa2.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKa2\ T10 S1
.\Release\gcCompare.exe BB AKa3.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKa3\ T10 S1
.\Release\gcCompare.exe BB AKa4.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKa4\ T10 S1
.\Release\gcCompare.exe BB AKs3.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKs3\ T9 S1
.\Release\gcCompare.exe BB AKs5.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKs5\ T10 S1
.\Release\gcCompare.exe BB AKs6.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKs6\ T10 S1
.\Release\gcCompare.exe BB AKs7.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKs7\ T10 S1
.\Release\gcCompare.exe BB AKs8.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\AKs8\ T10 S1
.\Release\gcCompare.exe BB Ble.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\Ble\ T9 S1
.\Release\gcCompare.exe BB C002.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\C002\ T6 S1
.\Release\gcCompare.exe BB case_2.nii Outline D:\Repo\PhDthesis\cr\BB-Heuristic\case_2\ T9 L5
.\Release\gcCompare.exe BB case_10.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\case_10\ T10 L5
.\Release\gcCompare.exe BB DzZ_T1.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\DzZ_T1\ T10 S1
.\Release\gcCompare.exe BB DzZ_T2.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\DzZ_T2\ T10 S1
.\Release\gcCompare.exe BB F02.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\F02\ T10 S1
.\Release\gcCompare.exe BB F03.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\F03\ T12 S1
.\Release\gcCompare.exe BB F04.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\F04\ T2 S1
.\Release\gcCompare.exe BB Geh.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\Geh\ T12 S1
.\Release\gcCompare.exe BB Hoe.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\Hoe\ T11 S1
.\Release\gcCompare.exe BB Lan.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\Lan\ T10 S1
.\Release\gcCompare.exe BB LanII.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\LanII\ T10 S1
.\Release\gcCompare.exe BB LC.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\LC\ T12 S1
.\Release\gcCompare.exe BB S01.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\S01\ T12 S1
.\Release\gcCompare.exe BB S02.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\S02\ T11 S1
.\Release\gcCompare.exe BB Sch.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\Sch\ T11 L5
.\Release\gcCompare.exe BB St1.dcm Outline D:\Repo\PhDthesis\cr\BB-Heuristic\St1\ T11 S1