.\Release\gcCompare.exe MF AKa2.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKa2\ T10 S1
.\Release\gcCompare.exe MF AKa3.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKa3\ T10 S1
.\Release\gcCompare.exe MF AKa4.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKa4\ T10 S1
.\Release\gcCompare.exe MF AKs3.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKs3\ T9 S1
.\Release\gcCompare.exe MF AKs5.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKs5\ T10 S1
.\Release\gcCompare.exe MF AKs6.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKs6\ T10 S1
.\Release\gcCompare.exe MF AKs7.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKs7\ T10 S1
.\Release\gcCompare.exe MF AKs8.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\AKs8\ T10 S1
.\Release\gcCompare.exe MF Ble.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\Ble\ T9 S1
.\Release\gcCompare.exe MF C002.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\C002\ T6 S1
.\Release\gcCompare.exe MF case_2.nii SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\case_2\ T9 L5
.\Release\gcCompare.exe MF case_10.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\case_10\ T10 L5
.\Release\gcCompare.exe MF DzZ_T1.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\DzZ_T1\ T10 S1
.\Release\gcCompare.exe MF DzZ_T2.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\DzZ_T2\ T10 S1
.\Release\gcCompare.exe MF F02.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\F02\ T10 S1
.\Release\gcCompare.exe MF F03.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\F03\ T12 S1
.\Release\gcCompare.exe MF F04.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\F04\ T2 S1
.\Release\gcCompare.exe MF Geh.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\Geh\ T12 S1
.\Release\gcCompare.exe MF Hoe.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\Hoe\ T11 S1
.\Release\gcCompare.exe MF Lan.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\Lan\ T10 S1
.\Release\gcCompare.exe MF LanII.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\LanII\ T10 S1
.\Release\gcCompare.exe MF LC.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\LC\ T12 S1
.\Release\gcCompare.exe MF S01.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\S01\ T12 S1
.\Release\gcCompare.exe MF S02.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\S02\ T11 S1
.\Release\gcCompare.exe MF Sch.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\Sch\ T11 L5
.\Release\gcCompare.exe MF St1.dcm SinglePoint D:\Repo\PhDthesis\cr\MF-SinglePoint\St1\ T11 S1