.\Release\gcCompare.exe BB AKa2.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKa2\ T10 S1
.\Release\gcCompare.exe BB AKa3.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKa3\ T10 S1
.\Release\gcCompare.exe BB AKa4.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKa4\ T10 S1
.\Release\gcCompare.exe BB AKs3.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKs3\ T9 S1
.\Release\gcCompare.exe BB AKs5.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKs5\ T10 S1
.\Release\gcCompare.exe BB AKs6.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKs6\ T10 S1
.\Release\gcCompare.exe BB AKs7.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKs7\ T10 S1
.\Release\gcCompare.exe BB AKs8.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\AKs8\ T10 S1
.\Release\gcCompare.exe BB Ble.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\Ble\ T9 S1
.\Release\gcCompare.exe BB C002.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\C002\ T6 S1
.\Release\gcCompare.exe BB case_2.nii Outline D:\Repo\PhDthesis\cr\BB-FreeForm\case_2\ T9 L5
.\Release\gcCompare.exe BB case_10.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\case_10\ T10 L5
.\Release\gcCompare.exe BB DzZ_T1.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\DzZ_T1\ T10 S1
.\Release\gcCompare.exe BB DzZ_T2.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\DzZ_T2\ T10 S1
.\Release\gcCompare.exe BB F02.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\F02\ T10 S1
.\Release\gcCompare.exe BB F03.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\F03\ T12 S1
.\Release\gcCompare.exe BB F04.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\F04\ T2 S1
.\Release\gcCompare.exe BB Geh.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\Geh\ T12 S1
.\Release\gcCompare.exe BB Hoe.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\Hoe\ T11 S1
.\Release\gcCompare.exe BB Lan.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\Lan\ T10 S1
.\Release\gcCompare.exe BB LanII.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\LanII\ T10 S1
.\Release\gcCompare.exe BB LC.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\LC\ T12 S1
.\Release\gcCompare.exe BB S01.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\S01\ T12 S1
.\Release\gcCompare.exe BB S02.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\S02\ T11 S1
.\Release\gcCompare.exe BB Sch.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\Sch\ T11 L5
.\Release\gcCompare.exe BB St1.dcm Outline D:\Repo\PhDthesis\cr\BB-FreeForm\St1\ T11 S1