.\Release\gcCompare.exe MF AKa2.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKa2\ T10 S1
.\Release\gcCompare.exe MF AKa3.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKa3\ T10 S1
.\Release\gcCompare.exe MF AKa4.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKa4\ T10 S1
.\Release\gcCompare.exe MF AKs3.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKs3\ T9 S1
.\Release\gcCompare.exe MF AKs5.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKs5\ T10 S1
.\Release\gcCompare.exe MF AKs6.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKs6\ T10 S1
.\Release\gcCompare.exe MF AKs7.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKs7\ T10 S1
.\Release\gcCompare.exe MF AKs8.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\AKs8\ T10 S1
.\Release\gcCompare.exe MF Ble.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\Ble\ T9 S1
.\Release\gcCompare.exe MF C002.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\C002\ T6 S1
.\Release\gcCompare.exe MF case_2.nii Outline D:\Repo\PhDthesis\cr\MF-Outline\case_2\ T9 L5
.\Release\gcCompare.exe MF case_10.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\case_10\ T10 L5
.\Release\gcCompare.exe MF DzZ_T1.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\DzZ_T1\ T10 S1
.\Release\gcCompare.exe MF DzZ_T2.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\DzZ_T2\ T10 S1
.\Release\gcCompare.exe MF F02.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\F02\ T10 S1
.\Release\gcCompare.exe MF F03.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\F03\ T12 S1
.\Release\gcCompare.exe MF F04.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\F04\ T2 S1
.\Release\gcCompare.exe MF Geh.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\Geh\ T12 S1
.\Release\gcCompare.exe MF Hoe.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\Hoe\ T11 S1
.\Release\gcCompare.exe MF Lan.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\Lan\ T10 S1
.\Release\gcCompare.exe MF LanII.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\LanII\ T10 S1
.\Release\gcCompare.exe MF LC.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\LC\ T12 S1
.\Release\gcCompare.exe MF S01.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\S01\ T12 S1
.\Release\gcCompare.exe MF S02.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\S02\ T11 S1
.\Release\gcCompare.exe MF Sch.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\Sch\ T11 L5
.\Release\gcCompare.exe MF St1.dcm Outline D:\Repo\PhDthesis\cr\MF-Outline\St1\ T11 S1