.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKa2.dcm D:\Repo\Segmented\AKa2\ D:\Publications\CGF-Spine\Data\AKa2\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKa3.dcm D:\Repo\Segmented\AKa3\ D:\Publications\CGF-Spine\Data\AKa3\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKa4.dcm D:\Repo\Segmented\AKa4\ D:\Publications\CGF-Spine\Data\AKa4\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKs3.dcm D:\Repo\Segmented\AKs3\ D:\Publications\CGF-Spine\Data\AKs3\ T9 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKs5.dcm D:\Repo\Segmented\AKs5\ D:\Publications\CGF-Spine\Data\AKs5\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKs6.dcm D:\Repo\Segmented\AKs6\ D:\Publications\CGF-Spine\Data\AKs6\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKs7.dcm D:\Repo\Segmented\AKs7\ D:\Publications\CGF-Spine\Data\AKs7\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\AKs8.dcm D:\Repo\Segmented\AKs8\ D:\Publications\CGF-Spine\Data\AKs8\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\Ble.dcm D:\Repo\Segmented\Ble\ D:\Publications\CGF-Spine\Data\Ble\ T9 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\C002.dcm D:\Repo\Segmented\C002\ D:\Publications\CGF-Spine\Data\C002\ T6 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\case_2.nii D:\Repo\Segmented\case_2\ D:\Publications\CGF-Spine\Data\case_2\ T9 L5
.\Release\gcCompare.exe D:\Repo\SpineDatasets\case_10.dcm D:\Repo\Segmented\case_10\ D:\Publications\CGF-Spine\Data\case_10\ T10 L5
.\Release\gcCompare.exe D:\Repo\SpineDatasets\DzZ_T1.dcm D:\Repo\Segmented\DzZ_T1\ D:\Publications\CGF-Spine\Data\DzZ_T1\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\DzZ_T2.dcm D:\Repo\Segmented\DzZ_T2\ D:\Publications\CGF-Spine\Data\DzZ_T2\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\F02.dcm D:\Repo\Segmented\F02\ D:\Publications\CGF-Spine\Data\F02\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\F03.dcm D:\Repo\Segmented\F03\ D:\Publications\CGF-Spine\Data\F03\ T12 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\F04.dcm D:\Repo\Segmented\F04\ D:\Publications\CGF-Spine\Data\F04\ T2 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\Geh.dcm D:\Repo\Segmented\Geh\ D:\Publications\CGF-Spine\Data\Geh\ T12 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\Hoe.dcm D:\Repo\Segmented\Hoe\ D:\Publications\CGF-Spine\Data\Hoe\ T11 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\Lan.dcm D:\Repo\Segmented\Lan\ D:\Publications\CGF-Spine\Data\Lan\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\LanII.dcm D:\Repo\Segmented\LanII\ D:\Publications\CGF-Spine\Data\LanII\ T10 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\LC.dcm D:\Repo\Segmented\lc\ D:\Publications\CGF-Spine\Data\LC\ T12 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\S01.dcm D:\Repo\Segmented\S01\ D:\Publications\CGF-Spine\Data\S01\ T12 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\S02.dcm D:\Repo\Segmented\S02\ D:\Publications\CGF-Spine\Data\S02\ T11 S1
.\Release\gcCompare.exe D:\Repo\SpineDatasets\Sch.dcm D:\Repo\Segmented\Sch\ D:\Publications\CGF-Spine\Data\Sch\ T11 L5
.\Release\gcCompare.exe D:\Repo\SpineDatasets\St1.dcm D:\Repo\Segmented\St1\ D:\Publications\CGF-Spine\Data\St1\ T11 S1